# NumPy

create numpy array


In [2]:
import numpy as np


In [4]:
A=np.array([1,2,3,4])
print(A)
print(type(A))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
A=np.array((1,2,3,4))
print(A)
print(type(A))

[1 2 3 4]
<class 'numpy.ndarray'>


# Dimensions in Arrays

# 0D Arrays

In [6]:
A=np.array(42)
print(A)
print(type(A))

42
<class 'numpy.ndarray'>


# 1D Arrays

In [7]:
A=np.array([1,2,3,4])
print(A)
print(type(A))

[1 2 3 4]
<class 'numpy.ndarray'>


# 2D Arrays

In [8]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
 a = np.array(42)
b =np.array([1,2,3,4])
c =np.array([[1,2,3],[4,5,6],[7,8,9]])
d =np.array([[[1,2],[4,5]],[[1,2],[4,5]]] )
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


# Higher Dimensional Arrays

In [20]:
E=np.array([1,2,3,4],ndmin=5)
print(E)

[[[[[1 2 3 4]]]]]


# NumPy Array Slicing

# For 1D Arrays


In [30]:
H=np.array([1,2,3,4,5,6,7,8,9,10])
print(H[1:len(H)-1])
print(H[1:-1])
print(H[-6:-9])
print(H[-4:-11:-3])
print(H[-6:-1:2])

[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[]
[7 4 1]
[5 7 9]


# 2D Arrays

In [46]:
G=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(G[:,:3])
print(G[1,2:])
print(G[1:,2:])
print(G[::-1,1::2])
print(G[::,1::2])


[[1 2 3]
 [6 7 8]]
[ 8  9 10]
[[ 8  9 10]]
[[7 9]
 [2 4]]
[[2 4]
 [7 9]]


# For 3D Arrays

In [58]:
R=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ,[[13,14,15],[16,17,18]]])
print(R[:,1:,1:2])
print(R[1:,::-1,-1:-3:-1])
print("--------------")
print(R[::2,::-1,::2])

[[[ 5]]

 [[11]]

 [[17]]]
[[[12 11]
  [ 9  8]]

 [[18 17]
  [15 14]]]
--------------
[[[ 4  6]
  [ 1  3]]

 [[16 18]
  [13 15]]]


# NumPy Array Shape : returns in tuple


In [59]:
R=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ,[[13,14,15],[16,17,18]]])
print(R.shape)

(3, 2, 3)


In [60]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x.shape)

(2, 5)


# NumPy Arrays Reshaping

# Case-1 : Reshape from 1D to 2D

In [69]:
S=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
S1=S.reshape(12,1)
print(S1)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


# Case-2:Reshape from 1D to 3D

In [70]:
P=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
P1=P.reshape(2,3,2) #1,1,12 ; 1,2,6 ; 1,3,4 ; 2,1,6 ; 12,1,1 ;  6,2,1 ; ,4,1,3

print(P1)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Reshape any Array into 1D (Flattening the Arrays)

In [71]:
K=np.array([[1,2,3],[4,5,6]])
K1=K.reshape(-1)
print(K1)


[1 2 3 4 5 6]


# Unknown Dimension

In [73]:
z=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
Z1=z.reshape(2,2,-1)
Z2=z.reshape(2,1,-1)
print(Z1)
print("---")
print(Z2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---
[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]


# NumPy Array iterating

In [76]:
a = np.array(42)
b =np.array([1,2,3,4])
c =np.array([[1,2,3],[4,5,6],[7,8,9]])
d =np.array([[[1,2],[4,5]],[[1,2],[4,5]]] )


for j in b:
    print(j,end=" ")
print("------------------------")
for k in c:
    for h in k:
        print(h,end=" ")
    print()
print("------------------------")

for i in d:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()

1 2 3 4 ------------------------
1 2 3 
4 5 6 
7 8 9 
------------------------
1 2 
4 5 
1 2 
4 5 


# NumPy joining Array

# concatenating 1D Array

In [77]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate((a1,a2))
print(a3)

[1 2 3 4 5 6]


# Concatenating 2D Arrays

# Case-1 axis=0


In [78]:
b1=np.array([[1,2],[3,4]])
b2=np.array([[5,6],[7,8]])
b3=np.concatenate((b1,b2),axis=0)  #horizontally
print(b3)
# https://termnet-live.onrender.com

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Case-2 axis=1

In [79]:
b1=np.array([[1,2],[3,4]])
b2=np.array([[5,6],[7,8]])
b3=np.concatenate((b1,b2),axis=1)  #vertically
print(b3)


[[1 2 5 6]
 [3 4 7 8]]


# Concatenating 3D Arrays

In [3]:
arr1 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print('arr1')
print(arr1)
arr2 = np.array([9,10,11,12,13,14,15,16])
arr2 = arr2.reshape(2,2,2)
print('arr2')
print(arr2)
arr = np.concatenate((arr1, arr2), axis=2)
print('ans')
print(arr)

arr1
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
arr2
[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
ans
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


# NumPy Spliting Array

# Spliting 1D Array

In [5]:
import numpy as np
A=np.array([1,2,3,4,5,6])
A1=np.array_split(A,5)
print(A1)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [7]:
import numpy as np
A=np.array([1,2,3,4,5,6])
A1=np.array_split(A,8)
print(A1)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


# Spliting 2D Array

In [10]:
B=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
B1=np.array_split(B,5)
print(B1)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32), array([], shape=(6, 0), dtype=int32), array([], shape=(6, 0), dtype=int32)]


In [22]:
B=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
B1=np.array_split(B,3,axis=1)
print(B1)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [18]:
B

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# where function

In [24]:
#returns index nummber
D=np.array([1,2,3,4,5,4,6,4,4])
x=np.where(D==4)
print(x)

(array([3, 5, 7, 8], dtype=int64),)


In [25]:
D=np.array([1,2,3,4,5,4,6,4,4])
x=np.where(D%2==1)
print(x)

(array([0, 2, 4], dtype=int64),)


# Numpy sorting arrays

# case-1 : sorting 1D Array

In [26]:
arr = np.array([3, 2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [27]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [28]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


# Case:2 Sorting 2D Arrays

In [30]:
S= np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(S))

[[2 3 4]
 [0 1 5]]


# Case:3 Sorting 3D Arrays

In [31]:
S= np.array([[[3, 2, 4], [5, 0, 1]], [[3, 2, 4], [5, 0, 1]]])
print(np.sort(S))

[[[2 3 4]
  [0 1 5]]

 [[2 3 4]
  [0 1 5]]]


# Descending order

In [32]:
arr = np.array([3, 2,0,1])
print(np.sort(arr)[::-1])

[3 2 1 0]


In [34]:
S= np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(S)[:,::-1])

[[4 3 2]
 [5 1 0]]


In [36]:
S= np.array([[[3, 2, 4], [5, 0, 1]], [[3, 2, 4], [5, 0, 1]]])
print(np.sort(S)[:,:,::-1])

[[[4 3 2]
  [5 1 0]]

 [[4 3 2]
  [5 1 0]]]


# Random Module

In [51]:
from numpy import random
x=random.randint(30,40)
print(x)

33


In [52]:
from numpy import random
x=random.rand()
print(x)

0.51807483922847


In [55]:
from numpy import random
x=random.randint(20,40,size=(5,9))
print(x)

[[27 28 26 32 21 23 32 35 27]
 [39 30 32 23 31 36 23 23 37]
 [37 33 22 35 39 22 20 31 34]
 [25 26 30 26 36 24 31 32 38]
 [22 38 22 39 20 32 30 21 22]]


In [56]:
from numpy import random
x=random.rand(5)
print(x)

[0.89416833 0.56435239 0.54907456 0.04122452 0.56891983]


In [57]:
from numpy import random
x=random.rand(3,3)
print(x)

[[0.80592619 0.12341842 0.5890862 ]
 [0.7960629  0.7388076  0.54059064]
 [0.8466282  0.15407674 0.32101075]]


In [60]:
y=random.choice([3,5,7,9])
print(y)

7


In [61]:
y=random.choice([3,5,7,9],size=(3,5))
print(y)

[[7 7 9 5 5]
 [9 5 7 5 3]
 [3 9 7 3 5]]


#Write a python program to prepare number-guessing game by using numpy random module

In [63]:
from numpy import random
guess_number=random.randint(100)
attempts=5
print("Number Guessing game")
print("Guess a number between 1 and 100")
print("you have",attempts,"attempts")
for i in range(0,attempts+1):
    user_number=int(input("Enter the number:"))
    if user_number==guess_number:
        print("Correct! you won in",i,"attempts")
        break
    elif user_number<guess_number:
        print("TO LOW!")
    else:
        print("TO HIGH!")
else:
    print("Game Over! The number was:",guess_number)


Number Guessing game
Guess a number between 1 and 100
you have 5 attempts
Enter the number:1
TO LOW!
Enter the number:2
TO LOW!
Enter the number:3
TO LOW!
Enter the number:4
TO LOW!
Enter the number:66
TO HIGH!
Enter the number:70
TO HIGH!
Game Over! The number was: 13


In [ ]:
import matplotlib.pyplot as plt
 # Subplot 1
 plt.subplot(3, 2, 1)
 x_values = [5, 10, 25, 60, 80]
 y_values = [5, 17, 25, 40, 30]
 plt.plot(x_values, y_values, color='green', linestyle='dotted', marker='D')
 plt.xlabel('X-axis')
 plt.ylabel('Y-axis')
 plt.title('Line Plot with Dotted Line and Diamond Marker')
 # Subplot 2
 plt.subplot(3, 2, 2)
 Scores_men = (22, 30, 35, 35, 26)
 Scores_women = (25, 32, 30, 35, 29)
 groups = ['Group 1', 'Group 2', 'Group 3', 'Group 4', 'Group 5']
 bar_width = 0.35
 bar_positions_men = range(len(groups))
 bar_positions_women = [pos + bar_width for pos in bar_positions_men]
 # Subplot 3
 plt.bar(bar_positions_men, Scores_men, color='green', width=bar_width,␣
 ↪label='Men')
 plt.bar(bar_positions_women, Scores_women, color='red', width=bar_width,␣
 ↪label='Women')
 plt.xlabel('Groups')
 plt.ylabel('Scores')
 plt.title('Bar Plot of Scores by Group and Gender')
 # plt.xticks([pos + bar_width / 2 for pos in bar_positions_men], groups)
 # plt.legend(fontsize='small')
 plt.subplot(3, 2, 3)
 car_labels = ['Maruti Suzuki', 'Hyundai', 'Kia', 'Toyota', 'Honda']
 popularity = [25, 50, 30, 20, 35]
 plt.pie(popularity, labels=car_labels, autopct='%1.1f%%', startangle=90)
 plt.title('Popularity of Car Companies')
 # Subplot 4
 plt.subplot(3, 2, 4)
 math_marks = [88, 92, 80, 89, 100, 80, 60, 100, 80, 34]

science_marks = [35, 79, 79, 48, 100, 88, 32, 45, 20, 30]
 plt.scatter(range(1, 11), math_marks, marker='o', color='yellow',␣
 ↪label='Mathematics')
 plt.scatter(range(1, 11), science_marks, marker='*', color='blue',␣
 ↪label='Science')
 plt.xlabel('Students')
 plt.ylabel('Marks')
 plt.title('Scatter Plot: Mathematics vs Science')
 # plt.legend(fontsize='small')
 # Subplot 5
 plt.subplot(3, 2, 5)
 languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C', 'C++']
 popularity_languages = [20, 100, 25, 30, 45, 50]
 plt.barh(languages, popularity_languages, color=['orange', 'green', 'blue',␣
 ↪'red', 'purple', 'pink'])
 plt.xlabel('Popularity')
 plt.ylabel('Prog Lang')
 plt.title('Popularity of Programming Languages')
 # Subplot 6
 plt.subplot(3, 2, 6)
 data_histogram = [10, 20, 20, 30, 30, 30, 40, 40, 40, 40, 50, 50, 50, 60, 60,␣
 ↪70]
 plt.hist(data_histogram, color='red', bins=10, edgecolor='black')
 plt.xlabel('Values')
 plt.ylabel('Frequency')
 plt.title('Histogram Chart')
 plt.tight_layout(w_pad=20.0) # Increase both vertical and horizontal spacing,␣
 ↪add rect parameter for title
 plt.show()